// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF1r7TDY5M5aZuLxbB_yLFtGYLlx-eolM',
    appId: '1:343616982546:web:5544e59b050f8fc2d392cb',
    messagingSenderId: '343616982546',
    projectId: 'flutter-note-taker-b2804',
    authDomain: 'flutter-note-taker-b2804.firebaseapp.com',
    storageBucket: 'flutter-note-taker-b2804.appspot.com',
    measurementId: 'G-2ZZHD5N338',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBg5Th7VmlsWlF7OsD-Qdr2STFGmH2dww',
    appId: '1:343616982546:android:4eeee044f0741624d392cb',
    messagingSenderId: '343616982546',
    projectId: 'flutter-note-taker-b2804',
    storageBucket: 'flutter-note-taker-b2804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALqAVq8M_Lqo7oBgXmbnsEMRxSdAZtSzU',
    appId: '1:343616982546:ios:73e4debb7fe70ec7d392cb',
    messagingSenderId: '343616982546',
    projectId: 'flutter-note-taker-b2804',
    storageBucket: 'flutter-note-taker-b2804.appspot.com',
    iosClientId: '343616982546-hud2rnup3t00nd2bqe89vj58lelj7hou.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteTaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALqAVq8M_Lqo7oBgXmbnsEMRxSdAZtSzU',
    appId: '1:343616982546:ios:73e4debb7fe70ec7d392cb',
    messagingSenderId: '343616982546',
    projectId: 'flutter-note-taker-b2804',
    storageBucket: 'flutter-note-taker-b2804.appspot.com',
    iosClientId: '343616982546-hud2rnup3t00nd2bqe89vj58lelj7hou.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteTaker',
  );
}
